"""
utils/nginx_templates.py — Nginx config string generators.
No business logic here — pure string generation only.
"""
import config


def static_site_config(domain: str, webroot: str) -> str:
    """
    HTTP-only nginx config for a static site domain.
    Serves files from webroot.
    Includes /.well-known/acme-challenge/ for certbot HTTP-01.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    root {webroot};
    index index.html;

    # Certbot HTTP-01 challenge (shared acme dir)
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def static_site_ssl_config(domain: str, webroot: str, cert_path: str, key_path: str) -> str:
    """
    HTTP + HTTPS nginx config for a static site domain with SSL.
    HTTP redirects to HTTPS.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain} (SSL)

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain} www.{domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root {webroot};
    index index.html;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def reverse_proxy_config(full_domain: str, target_ip: str, target_port: int,
                          protocol: str) -> str:
    """
    HTTP-only nginx reverse proxy config for a subdomain.
    Includes acme-challenge location for optional SSL later.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    return f"""# Generated by srv-panel — do not edit manually
# Reverse proxy: {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}
}}
"""


def reverse_proxy_ssl_config(full_domain: str, target_ip: str, target_port: int,
                               protocol: str, cert_path: str, key_path: str) -> str:
    """
    HTTP + HTTPS nginx reverse proxy config with SSL.
    HTTP redirects to HTTPS.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    return f"""# Generated by srv-panel — do not edit manually
# Reverse proxy (SSL): {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {full_domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}
}}
"""


def default_index_html(domain: str) -> str:
    """Default index.html placed in webroot when domain is created."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{domain}</title>
  <style>
    *{{ box-sizing:border-box; margin:0; padding:0; }}
    body{{ font-family: system-ui, sans-serif; background:#0B0C0B; color:#E6E6DF;
          display:flex; align-items:center; justify-content:center; min-height:100vh; }}
    .box{{ text-align:center; padding:48px 32px; border:1px solid #2a2a2a; max-width:480px; }}
    h1{{ font-size:22px; font-weight:800; color:#C7F464; margin-bottom:12px; }}
    p{{ font-size:13px; color:#6B6F6A; line-height:1.6; }}
    .domain{{ font-size:14px; color:#DDEDE0; margin-top:16px; font-weight:600; }}
  </style>
</head>
<body>
  <div class="box">
    <h1>Site Coming Soon</h1>
    <p>This domain is configured and ready.<br>Upload your files or deploy your application.</p>
    <p class="domain">{domain}</p>
  </div>
</body>
</html>
"""
