"""
utils/nginx_templates.py — Nginx config string generators.
No business logic here — pure string generation only.
"""
import config


def static_site_config(domain: str, webroot: str) -> str:
    """
    HTTP-only nginx config for a static site domain.
    Serves files from webroot.
    Includes /.well-known/acme-challenge/ for certbot HTTP-01.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    root {webroot};
    index index.html;

    # Certbot HTTP-01 challenge (shared acme dir)
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def static_site_ssl_config(domain: str, webroot: str, cert_path: str, key_path: str) -> str:
    """
    HTTP + HTTPS nginx config for a static site domain with SSL.
    HTTP redirects to HTTPS.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain} (SSL)

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain} www.{domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root {webroot};
    index index.html;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def reverse_proxy_config(full_domain: str, target_ip: str, target_port: int,
                          protocol: str) -> str:
    """
    HTTP-only nginx reverse proxy config for a subdomain.
    Includes acme-challenge location for optional SSL later.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    return f"""# Generated by srv-panel — do not edit manually
# Reverse proxy: {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}
}}
"""


def reverse_proxy_ssl_config(full_domain: str, target_ip: str, target_port: int,
                               protocol: str, cert_path: str, key_path: str) -> str:
    """
    HTTP + HTTPS nginx reverse proxy config with SSL.
    HTTP redirects to HTTPS.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    return f"""# Generated by srv-panel — do not edit manually
# Reverse proxy (SSL): {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {full_domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}
}}
"""


def _panel_proxy_location(app_port: int) -> str:
    return f"""    location / {{
        proxy_pass         http://127.0.0.1:{app_port};
        proxy_http_version 1.1;
        # $http_host keeps :8080 etc. $host would strip the port and break redirects
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}"""


def _panel_acme_location() -> str:
    # root + URI path → /var/www/acme-challenge/.well-known/acme-challenge/<token>
    # matches certbot --webroot-path=/var/www/acme-challenge
    return f"""    location ^~ /.well-known/acme-challenge/ {{
        default_type "text/plain";
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}"""


def panel_site_config(
    server_ip: str,
    panel_domain: str | None,
    allow_ip: bool,
    ip_port: int,
    app_port: int,
    ssl: bool = False,
    cert_path: str | None = None,
    key_path: str | None = None,
) -> str:
    """
    Nginx config for the control panel itself (sites-available/panel).

    Security model (two separate doors):
    - IP  → only custom port (e.g. 8080). Port 80 by IP is free for websites.
    - Name → always panel on :80 (for LE + HTTP) and :443 after SSL.
      Never the Domain "Site Coming Soon" page for this hostname.
    """
    domain = (panel_domain or "").strip().lower()
    if not domain or domain in ("_", "localhost") or domain == (server_ip or "").strip():
        domain = ""

    if not domain and not allow_ip:
        # Safety net — caller should reject this; still produce IP:80
        allow_ip = True
        ip_port = 80

    blocks: list[str] = [
        "# Generated by srv-panel — panel UI",
        f"# Managed via Settings | SSL={ssl} allow_ip={allow_ip} ip_port={ip_port}",
        "# Hostname always uses ports 80/443. IP uses ip_port only (may be 8080).",
    ]

    # --- Hostname first (port 80/443) — required for Let's Encrypt ---
    if domain:
        if ssl and cert_path and key_path:
            blocks.append(f"""
# Panel hostname HTTP — ACME + redirect (not the Domain default HTML)
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

{_panel_acme_location()}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# Panel hostname HTTPS
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())
        else:
            blocks.append(f"""
# Panel hostname HTTP — full panel + ACME (until SSL is issued)
# This must NOT be a Domain static "Site Coming Soon" vhost.
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())

    # --- IP access on custom port only (e.g. 8080) — never steals hostname :80 ---
    if allow_ip and server_ip:
        acme = _panel_acme_location() if (ip_port == 80 and not domain) else ""
        if ip_port == 80:
            listen_lines = "    listen 80;\n    listen [::]:80;"
        else:
            listen_lines = f"    listen {ip_port};\n    listen [::]:{ip_port};"
        blocks.append(f"""
# Panel by IP only (custom port {ip_port}) — websites keep port 80
server {{
{listen_lines}
    server_name {server_ip};

{acme}

{_panel_proxy_location(app_port)}
}}
""".strip())

    if not domain and not (allow_ip and server_ip):
        # Last resort catch-all (dev)
        blocks.append(f"""
server {{
    listen 80;
    listen [::]:80;
    server_name _;

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())

    return "\n\n".join(blocks) + "\n"


def default_index_html(domain: str) -> str:
    """Default index.html placed in webroot when domain is created."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{domain}</title>
  <style>
    *{{ box-sizing:border-box; margin:0; padding:0; }}
    body{{ font-family: system-ui, sans-serif; background:#0B0C0B; color:#E6E6DF;
          display:flex; align-items:center; justify-content:center; min-height:100vh; }}
    .box{{ text-align:center; padding:48px 32px; border:1px solid #2a2a2a; max-width:480px; }}
    h1{{ font-size:22px; font-weight:800; color:#C7F464; margin-bottom:12px; }}
    p{{ font-size:13px; color:#6B6F6A; line-height:1.6; }}
    .domain{{ font-size:14px; color:#DDEDE0; margin-top:16px; font-weight:600; }}
  </style>
</head>
<body>
  <div class="box">
    <h1>Site Coming Soon</h1>
    <p>This domain is configured and ready.<br>Upload your files or deploy your application.</p>
    <p class="domain">{domain}</p>
  </div>
</body>
</html>
"""
