"""
utils/nginx_templates.py — Nginx config string generators.
No business logic here — pure string generation only.
"""
import re
import config


def _safe_zone(full_domain: str) -> str:
    """Safe nginx zone/path name from a domain (max 32 chars)."""
    sanitized = re.sub(r"[^a-z0-9]", "_", full_domain.lower())
    return f"prx_{sanitized}"[:32]


def performance_conf(gzip: bool, static_cache: bool) -> str:
    """
    Global performance settings for /etc/nginx/conf.d/performance.conf.
    Applied in the nginx http{} context — affects all virtual hosts.
    """
    parts = ["# Generated by srv-panel — do not edit manually", "# Global performance settings", ""]

    if gzip:
        parts += [
            "# 'gzip on;' is omitted because it is enabled by default in nginx.conf",
            "gzip_vary on;",
            "gzip_min_length 1024;",
            "gzip_comp_level 5;",
            "gzip_proxied any;",
            "gzip_types",
            "    text/plain text/css text/xml text/javascript",
            "    application/json application/javascript application/xml+rss",
            "    application/x-javascript image/svg+xml font/ttf font/otf;",
            "",
        ]

    if static_cache:
        parts += [
            "# Browser cache map for static asset types",
            "map $sent_http_content_type $srv_expires {",
            "    default                         off;",
            "    ~*text/css                       1y;",
            "    ~*application/javascript         1y;",
            "    ~*image/                         1y;",
            "    ~*font/                          1y;",
            "    ~*application/font-woff          1y;",
            "    ~*image/svg\\+xml                 1y;",
            "}",
            "",
        ]

    if not gzip and not static_cache:
        parts.append("# No performance optimizations active")

    return "\n".join(parts) + "\n"


def proxy_cache_zone_header(full_domain: str, ttl_minutes: int) -> str:
    """
    proxy_cache_path directive for a specific proxy domain.
    Must appear before server{} blocks (valid in http context via sites-enabled include).
    """
    zone = _safe_zone(full_domain)
    cache_path = f"{config.NGINX_CACHE_DIR}/{zone}"
    return (
        f"proxy_cache_path {cache_path} "
        f"levels=1:2 keys_zone={zone}:10m "
        f"inactive={ttl_minutes}m max_size=500m use_temp_path=off;\n"
    )


def _proxy_cache_location_directives(full_domain: str, ttl_minutes: int) -> str:
    """Cache directives to inject inside a proxy location{} block."""
    zone = _safe_zone(full_domain)
    return f"""\
        proxy_cache            {zone};
        proxy_cache_valid      200 301 302 {ttl_minutes}m;
        proxy_cache_valid      any 1m;
        proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock       on;
        proxy_cache_bypass     $http_pragma $http_authorization;
        proxy_no_cache         $http_pragma $http_authorization;
        add_header             X-Cache-Status $upstream_cache_status;"""


def _static_cache_location(static_cache: bool, upstream: str) -> str:
    """Extra location block for browser-caching static file types through the proxy."""
    if not static_cache:
        return ""
    return f"""
    location ~* \\.(css|js|woff2?|ttf|otf|eot|svg|png|jpg|jpeg|gif|ico|webp)$ {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host            $http_host;
        proxy_set_header   X-Real-IP       $remote_addr;
        expires            1y;
        add_header         Cache-Control   "public, immutable";
        access_log         off;
    }}"""


def static_site_config(domain: str, webroot: str) -> str:
    """
    HTTP-only nginx config for a static site domain.
    Serves files from webroot.
    Includes /.well-known/acme-challenge/ for certbot HTTP-01.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    root {webroot};
    index index.html;

    # Certbot HTTP-01 challenge (shared acme dir)
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def static_site_ssl_config(domain: str, webroot: str, cert_path: str, key_path: str) -> str:
    """
    HTTP + HTTPS nginx config for a static site domain with SSL.
    HTTP redirects to HTTPS.
    """
    return f"""# Generated by srv-panel — do not edit manually
# Domain: {domain} (SSL)

server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain} www.{domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    root {webroot};
    index index.html;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}
}}
"""


def reverse_proxy_config(
    full_domain: str,
    target_ip: str,
    target_port: int,
    protocol: str,
    *,
    cache_enabled: bool = False,
    cache_ttl_minutes: int = 10,
    static_cache: bool = False,
) -> str:
    """
    HTTP-only nginx reverse proxy config for a subdomain.
    Includes acme-challenge location for optional SSL later.
    Optionally adds proxy_cache zone and browser cache location.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    cache_header = proxy_cache_zone_header(full_domain, cache_ttl_minutes) if cache_enabled else ""
    cache_directives = _proxy_cache_location_directives(full_domain, cache_ttl_minutes) if cache_enabled else ""
    static_loc = _static_cache_location(static_cache and config.NGINX_PERF_STATIC_CACHE, upstream)

    return f"""{cache_header}# Generated by srv-panel — do not edit manually
# Reverse proxy: {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    # Certbot HTTP-01 challenge
    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
{cache_directives}
    }}{static_loc}
}}
"""



def reverse_proxy_ssl_config(
    full_domain: str,
    target_ip: str,
    target_port: int,
    protocol: str,
    cert_path: str,
    key_path: str,
    *,
    cache_enabled: bool = False,
    cache_ttl_minutes: int = 10,
    static_cache: bool = False,
) -> str:
    """
    HTTP + HTTPS nginx reverse proxy config with SSL.
    HTTP redirects to HTTPS. Optionally adds proxy cache and static asset caching.
    """
    upstream = f"{protocol}://{target_ip}:{target_port}"
    cache_header = proxy_cache_zone_header(full_domain, cache_ttl_minutes) if cache_enabled else ""
    cache_directives = _proxy_cache_location_directives(full_domain, cache_ttl_minutes) if cache_enabled else ""
    static_loc = _static_cache_location(static_cache and config.NGINX_PERF_STATIC_CACHE, upstream)

    return f"""{cache_header}# Generated by srv-panel — do not edit manually
# Reverse proxy (SSL): {full_domain} → {upstream}

server {{
    listen 80;
    listen [::]:80;
    server_name {full_domain};

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {full_domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    location /.well-known/acme-challenge/ {{
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}

    location / {{
        proxy_pass         {upstream};
        proxy_http_version 1.1;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
{cache_directives}
    }}{static_loc}
}}
"""



def _panel_proxy_location(app_port: int) -> str:
    return f"""    location / {{
        proxy_pass         http://127.0.0.1:{app_port};
        proxy_http_version 1.1;
        # $http_host keeps :8080 etc. $host would strip the port and break redirects
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   X-Forwarded-Host  $http_host;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }}"""


def _panel_acme_location() -> str:
    # root + URI path → /var/www/acme-challenge/.well-known/acme-challenge/<token>
    # matches certbot --webroot-path=/var/www/acme-challenge
    return f"""    location ^~ /.well-known/acme-challenge/ {{
        default_type "text/plain";
        root {config.NGINX_WEBROOT}/acme-challenge;
        try_files $uri =404;
    }}"""


def panel_site_config(
    server_ip: str,
    panel_domain: str | None,
    allow_ip: bool,
    ip_port: int,
    app_port: int,
    ssl: bool = False,
    cert_path: str | None = None,
    key_path: str | None = None,
) -> str:
    """
    Nginx config for the control panel itself (sites-available/panel).

    Security model (two separate doors):
    - IP  → only custom port (e.g. 8080). Port 80 by IP is free for websites.
    - Name → always panel on :80 (for LE + HTTP) and :443 after SSL.
      Never the Domain "Site Coming Soon" page for this hostname.
    """
    domain = (panel_domain or "").strip().lower()
    if not domain or domain in ("_", "localhost") or domain == (server_ip or "").strip():
        domain = ""

    if not domain and not allow_ip:
        # Safety net — caller should reject this; still produce IP:80
        allow_ip = True
        ip_port = 80

    blocks: list[str] = [
        "# Generated by srv-panel — panel UI",
        f"# Managed via Settings | SSL={ssl} allow_ip={allow_ip} ip_port={ip_port}",
        "# Hostname always uses ports 80/443. IP uses ip_port only (may be 8080).",
    ]

    # --- Hostname first (port 80/443) — required for Let's Encrypt ---
    if domain:
        if ssl and cert_path and key_path:
            blocks.append(f"""
# Panel hostname HTTP — ACME + redirect (not the Domain default HTML)
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

{_panel_acme_location()}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}

# Panel hostname HTTPS
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain};

    ssl_certificate     {cert_path};
    ssl_certificate_key {key_path};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())
        else:
            blocks.append(f"""
# Panel hostname HTTP — full panel + ACME (until SSL is issued)
# This must NOT be a Domain static "Site Coming Soon" vhost.
server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())

    # --- IP access on custom port only (e.g. 8080) — never steals hostname :80 ---
    if allow_ip and server_ip:
        acme = _panel_acme_location() if (ip_port == 80 and not domain) else ""
        if ip_port == 80:
            listen_lines = "    listen 80;\n    listen [::]:80;"
        else:
            listen_lines = f"    listen {ip_port};\n    listen [::]:{ip_port};"
        blocks.append(f"""
# Panel by IP only (custom port {ip_port}) — websites keep port 80
server {{
{listen_lines}
    server_name {server_ip};

{acme}

{_panel_proxy_location(app_port)}
}}
""".strip())

    if not domain and not (allow_ip and server_ip):
        # Last resort catch-all (dev)
        blocks.append(f"""
server {{
    listen 80;
    listen [::]:80;
    server_name _;

{_panel_acme_location()}

{_panel_proxy_location(app_port)}
}}
""".strip())

    return "\n\n".join(blocks) + "\n"


def default_index_html(domain: str) -> str:
    """Default index.html placed in webroot when domain is created."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{domain}</title>
  <style>
    *{{ box-sizing:border-box; margin:0; padding:0; }}
    body{{ font-family: system-ui, sans-serif; background:#0B0C0B; color:#E6E6DF;
          display:flex; align-items:center; justify-content:center; min-height:100vh; }}
    .box{{ text-align:center; padding:48px 32px; border:1px solid #2a2a2a; max-width:480px; }}
    h1{{ font-size:22px; font-weight:800; color:#C7F464; margin-bottom:12px; }}
    p{{ font-size:13px; color:#6B6F6A; line-height:1.6; }}
    .domain{{ font-size:14px; color:#DDEDE0; margin-top:16px; font-weight:600; }}
  </style>
</head>
<body>
  <div class="box">
    <h1>Site Coming Soon</h1>
    <p>This domain is configured and ready.<br>Upload your files or deploy your application.</p>
    <p class="domain">{domain}</p>
  </div>
</body>
</html>
"""
